# Generated by Django 5.2.7 on 2025-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.CharField(blank=True, help_text="Eğer 'Tekli Seçim' yaptıysanız seçenekleri virgülle ayırarak yazın. Örn: Evet, Hayır, Kısmen", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Metin Cevap'), ('star', 'Yıldız Puanlama (1-5)'), ('choice', 'Tekli Seçim (Dropdown)')], default='text', max_length=20),
        ),
    ]
