# Generated by Django 5.2.7 on 2025-12-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_options_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='page_number',
            field=models.IntegerField(default=1, verbose_name='Sayfa Numarası'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='Seçenekleri virgülle ayırın', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Kısa Metin'), ('star', 'Yıldız Puanlama'), ('choice', 'Tek Seçim (Radio)'), ('multiple', 'Çoklu Seçim (Checkbox)'), ('date', 'Tarih Seçimi'), ('scale', '1-10 Ölçek')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
