# Generated by Django 5.2.7 on 2026-01-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_options_question_page_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Zorunlu Soru'),
        ),
    ]
