# Generated by Django 5.2.7 on 2025-11-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_full_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.menu'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='meal',
        ),
    ]
