# Generated by Django 5.2.7 on 2026-01-14 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


import json

def convert_options_to_json(apps, schema_editor):
    Question = apps.get_model('api', 'Question')
    for q in Question.objects.all():
        if q.options:
            # "A, B, C" -> ["A", "B", "C"]
            # Eğer zaten JSON gibi görünüyorsa dokunma (bu case zor ama önlem)
            try:
                # Zaten valid bir json mu diye bak
                json.loads(q.options)
            except ValueError:
                # Değilse virgülle ayırıp listeye çevir ve stringify et
                parts = [opt.strip() for opt in q.options.split(',') if opt.strip()]
                q.options = json.dumps(parts) 
                q.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(convert_options_to_json),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='Seçenekler listesi', null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
