# Generated by Django 5.2.7 on 2025-11-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_surveyanswer_unique_together_surveyanswer_menu_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyanswer',
            unique_together={('user', 'menu')},
        ),
    ]
