# Generated by Django 5.2.7 on 2026-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_options_alter_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='numeric_value',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
