"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url
from dotenv import load_dotenv

load_dotenv() # .env dosyasını yükle

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- 3. Parti Uygulamalar ---
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',

    #--- Bizim Uygulamalarımız ---
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'yemekhane_db'),
        'USER': os.getenv('DB_USER', 'yemekhane_user'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Testing: Use SQLite to avoid "Permission Denied" on generic Postgres users
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#AUTH_USER_MODEL = 'api.User'

# Frontend'imizin (Vite/React) çalıştığı adrese izin veriyoruz.
# Frontend'imizin (Vite/React) çalıştığı adrese izin veriyoruz.
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173').split(',')

# Frontend'in bize hangi BAŞLIKLARI (headers) yollamasına izin verdiğimizi
# açıkça belirtiyoruz. Bu, 'preflight' (OPTIONS) isteği için gereklidir.
CORS_ALLOW_HEADERS = [
    'authorization',  # Jetonumuzu (Token) yollamak için
    'content-type',   # JSON yollamak için

    # (Aşağıdakiler, 'corsheaders'ın varsayılan olarak izin verdikleridir,
    #  ama biz açıkça belirterek garantilemiş oluyoruz)
    'accept',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Frontend'in hangi METOTLARI kullanmasına izin verdiğimizi belirtiyoruz.
# 'OPTIONS' (preflight) metoduna izin vermek kritiktir.
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS' # Preflight isteğinin kendisi için
]

# Django REST Framework'ün varsayılan ayarlarını yapılandırma
REST_FRAMEWORK = {
    # Varsayılan Kimlik Doğrulama Sınıfları
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 1. Öncelik: Jeton (Token) ile kimlik doğrulamayı dene
        'rest_framework.authentication.TokenAuthentication', 

        # 2. Öncelik: Oturum (Session) ile kimlik doğrulamayı dene
        # (Bu, DRF'in 'Taranabilir API' arayüzünde (tarayıcıda) 
        # hala giriş yapabilmemizi sağlar - Çok kullanışlıdır!)
        'rest_framework.authentication.SessionAuthentication',
    ],

    # Varsayılan İzin Sınıfları
    # (Şimdilik 'AllowAny' (Herkese İzin Ver) olarak bırakabiliriz,
    # çünkü izinleri 'views.py' içinde (get_permissions) 
    # tek tek, eylem bazlı yönetiyoruz. Bu daha 'temiz' bir yaklaşımdır.)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True # Sadece Development ortamında açık kalsın
else:
    CORS_ALLOW_ALL_ORIGINS = False

# --- SMTP AYARLARI (GMAIL) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@ozal.edu.tr')