"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9v$81+r(ganv7o68e&z^xfj-stz!eo_k!co_u-0bte*s@1_s7p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- 3. Parti Uygulamalar ---
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',

    #--- Bizim Uygulamalarımız ---
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # SQLite değil, PostgreSQL kullan diyoruz
        'NAME': 'yemekhane_db',                     # pgAdmin'de oluşturduğumuz veritabanı adı
        'USER': 'yemekhane_user',                   # pgAdmin'de oluşturduğumuz kullanıcı adı
        'PASSWORD': 'user1',                        # yemekhane_user için belirlediğiniz şifre
        'HOST': 'localhost',                        # Veritabanı kendi bilgisayarımızda (localhost)
        'PORT': '5432',                             # Standart PostgreSQL portumuz
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#AUTH_USER_MODEL = 'api.User'

# Frontend'imizin (Vite/React) çalıştığı adrese izin veriyoruz.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Frontend'in bize hangi BAŞLIKLARI (headers) yollamasına izin verdiğimizi
# açıkça belirtiyoruz. Bu, 'preflight' (OPTIONS) isteği için gereklidir.
CORS_ALLOW_HEADERS = [
    'authorization',  # Jetonumuzu (Token) yollamak için
    'content-type',   # JSON yollamak için

    # (Aşağıdakiler, 'corsheaders'ın varsayılan olarak izin verdikleridir,
    #  ama biz açıkça belirterek garantilemiş oluyoruz)
    'accept',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Frontend'in hangi METOTLARI kullanmasına izin verdiğimizi belirtiyoruz.
# 'OPTIONS' (preflight) metoduna izin vermek kritiktir.
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS' # Preflight isteğinin kendisi için
]

# Django REST Framework'ün varsayılan ayarlarını yapılandırma
REST_FRAMEWORK = {
    # Varsayılan Kimlik Doğrulama Sınıfları
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 1. Öncelik: Jeton (Token) ile kimlik doğrulamayı dene
        'rest_framework.authentication.TokenAuthentication', 

        # 2. Öncelik: Oturum (Session) ile kimlik doğrulamayı dene
        # (Bu, DRF'in 'Taranabilir API' arayüzünde (tarayıcıda) 
        # hala giriş yapabilmemizi sağlar - Çok kullanışlıdır!)
        'rest_framework.authentication.SessionAuthentication',
    ],

    # Varsayılan İzin Sınıfları
    # (Şimdilik 'AllowAny' (Herkese İzin Ver) olarak bırakabiliriz,
    # çünkü izinleri 'views.py' içinde (get_permissions) 
    # tek tek, eylem bazlı yönetiyoruz. Bu daha 'temiz' bir yaklaşımdır.)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}